### ISSUE TITLE
关于网格搜索这一部分的问题

### ISSUE THREAD

**Issue by Times125** [davidlight2018/GAN_based_captcha_solver#1]
想请教一下，你在网格搜索具体实现是怎么做的呢？

**Comment by davidlight2018** [comment]
推荐你看一下这篇论文：Yet Another Text Captcha Solver A Generative Adversarial Network Based Approach

**Comment by Times125** [comment]
> 推荐你看一下这篇论文：Yet Another Text Captcha Solver A Generative Adversarial Network Based Approach

我就是看了这一部分，作者好像也没具体说呢

**Comment by davidlight2018** [comment]
看他论文里的意思是，每个参数都从很小的值开始（比如旋转、扭曲、位移等），每产生一组就训练一次，看能不能区分真的假的。然后不断往上增加，直到区分不出来为止。但是具体怎么实现的我也不清楚...
